### PR TITLE
Remove outdated or not working ref:FR:SIRET and ref:FR:SIREN keys

### PR DESCRIPTION
**Pull request by NathanBnm**
Search by link does not work anymore for https://infogreffe.fr/ and https://entreprise.data.gouv.fr is outdated and has been replaced by https://annuaire-entreprises.data.gouv.fr

### CODE REVIEW

**Comment by Cj-Malone** [comment]
Looks like this repo is just pulling the data from third parties, I think you should remove it from [here](https://www.wikidata.org/wiki/Property:P1616).

**Comment by NathanBnm** [comment]
@Cj-Malone thanks

**Comment by pyrog** [comment]
@NathanBnm You could set the rank to deprecated.

**Comment by nlehuby** [comment]
I think it have been done already, in both [SIRET](https://www.wikidata.org/wiki/Property:P3215) and [SIREN](https://www.wikidata.org/wiki/Property:P1616) page. How should we update this repo to take these changes into account ?

**Comment by tsmock** [comment]
Someone with write access needs to run `npm run build` and push the changes.

While I can _technically_ do that, I don't have the ability to update the NPM package.

**Pull request closed without merging**
