### PR TITLE
Added key ref:FR:ANFR

### PR DESCRIPTION
**Pull request by cayenne17**

### CODE REVIEW

**Comment by tsmock** [comment]
@cayenne17 : This repository gets data exclusively from third party locations, specifically
> - Wikidata items which have [OSM tag or key (P1282)](https://www.wikidata.org/wiki/Property:P1282) and [formatter URL (P1630)](https://www.wikidata.org/wiki/Property:P1630) defined
> - OSM Wiki Wikibase via the OSM Sophox Service which have [formatter URL (P8)](https://wiki.openstreetmap.org/wiki/Property:P8)

Please add the data to one of those two locations; the osm wiki data items is _probably_ the best place. See [Data_items#Item_creation_process](https://wiki.openstreetmap.org/wiki/Data_items#Item_creation_process) for details.

**Comment by cayenne17** [comment]
> @cayenne17 : This repository gets data exclusively from third party locations, specifically
> 
> > * Wikidata items which have [OSM tag or key (P1282)](https://www.wikidata.org/wiki/Property:P1282) and [formatter URL (P1630)](https://www.wikidata.org/wiki/Property:P1630) defined
> > * OSM Wiki Wikibase via the OSM Sophox Service which have [formatter URL (P8)](https://wiki.openstreetmap.org/wiki/Property:P8)
> 
> Please add the data to one of those two locations; the osm wiki data items is _probably_ the best place. See [Data_items#Item_creation_process](https://wiki.openstreetmap.org/wiki/Data_items#Item_creation_process) for details.

@tsmock It's good ? https://github.com/JOSM/tag2link/pull/5#issuecomment-1324140802

**Comment by tsmock** [comment]
Your change to Q19799 looks good.

Now we just have to wait for sophox.org to update their OSM wiki data. Once that happens, it should be in the next update of the tag2link package.

**Comment by cayenne17** [comment]
Hello
@tsmock When will this appear in JOSM?

**Comment by tsmock** [comment]
It should be there as of [18629](https://josm.openstreetmap.de/browser/josm/?rev=18629). So, it will be in the next josm-tested release (which I'm planning on doing Monday).

**Comment by tsmock** [comment]
I have to eat my words. No, it will not take an update of tag2link. Sophox isn't using the latest OSM WikiData, so it looks like I'm going to have to write a parser for RDF (I have to parse https://wiki.openstreetmap.org/dump/wikibase-rdf.ttl.gz ).

**Pull request closed without merging**
